import type { Category, Product, SpecEntry } from './types';

/**
 * SEED CATALOGUE — SAMPLE DATA, NOT REAL STOCK
 *
 * This is representative inventory used to build and demonstrate the store.
 * It is *not* Quattlebaum's real stock; the prices are illustrative MSRPs and
 * the stock counts are invented. Nothing here should be presented to a
 * customer as a live listing until it is replaced.
 *
 * Replace it by implementing a new source in `repository.ts` — a CMS, a POS
 * export, Square/Shopify inventory, or a database. Nothing outside that file
 * reads this array, so swapping the source does not touch the UI.
 */

/* ------------------------------------------------------------------ */
/* Departments                                                         */
/* ------------------------------------------------------------------ */

export const categories: Category[] = [
  {
    slug: 'electric-guitars',
    name: 'Electric Guitars',
    blurb: 'Solid bodies, semi-hollows, and the odd thing hanging in the corner.',
    plate: 'electric-guitar',
    weight: 'lead',
    group: 'guitars',
    image: {
      src: '/photos/demo/semi-hollow-guitar.jpg',
      alt: 'A cherry red semi-hollow electric guitar on a wood floor — demo photography, not shop stock',
    },
  },
  {
    slug: 'acoustic-guitars',
    name: 'Acoustic Guitars',
    blurb: 'Dreadnoughts, parlours, and first guitars that get played for years.',
    plate: 'acoustic-guitar',
    weight: 'major',
    group: 'guitars',
    image: {
      src: '/photos/demo/acoustic-guitar-1.jpg',
      alt: 'A natural-finish acoustic guitar leaning against a couch — demo photography, not shop stock',
    },
  },
  {
    slug: 'classical-guitars',
    name: 'Classical Guitars',
    blurb: 'Nylon strings, wide necks, and the quietest thing on the wall.',
    plate: 'acoustic-guitar',
    weight: 'minor',
    group: 'guitars',
    image: {
      src: '/photos/demo/classical-guitar.jpg',
      alt: 'A nylon-string classical guitar shown from the front and side — demo photography, not shop stock',
    },
  },
  {
    slug: 'ukuleles',
    name: 'Ukuleles',
    blurb: 'Soprano through baritone. The instrument nobody regrets buying.',
    plate: 'acoustic-guitar',
    weight: 'minor',
    group: 'guitars',
    image: {
      src: '/photos/demo/ukulele.jpg',
      alt: 'A vintage pearloid-finish ukulele — demo photography, not shop stock',
    },
  },
  {
    slug: 'bass',
    name: 'Basses',
    blurb: 'Four and five strings, short scale to long.',
    plate: 'bass',
    weight: 'minor',
    group: 'guitars',
    image: {
      src: '/photos/demo/bass-guitar-2.jpg',
      alt: 'A natural-finish electric bass guitar with a maple neck — demo photography, not shop stock',
    },
  },
  {
    slug: 'amplifiers',
    name: 'Amplifiers',
    blurb: 'Tube, solid state, and practice amps that will not wake the house.',
    plate: 'amplifier',
    weight: 'major',
    group: 'guitars',
    image: {
      src: '/photos/demo/amplifier-1.jpg',
      alt: 'A tolex-covered combo amplifier shown from the front and back — demo photography, not shop stock',
    },
  },
  {
    slug: 'pedals',
    name: 'Pedals & Effects',
    blurb: 'Dirt, delay, modulation. Plug in at the counter and find out.',
    plate: 'pedal',
    weight: 'minor',
    group: 'guitars',
    image: {
      src: '/photos/demo/pedal-1.jpg',
      alt: 'A green overdrive effects pedal — demo photography, not shop stock',
    },
  },
  {
    slug: 'keyboards',
    name: 'Keyboards & Pianos',
    blurb: 'Digital pianos, stage keys, and weighted actions worth sitting at.',
    plate: 'keyboard',
    weight: 'minor',
    group: 'keys',
    image: {
      src: '/photos/demo/keyboard-2.jpg',
      alt: 'A stacked pair of vintage electric pianos, shown in black and white — demo photography, not shop stock',
    },
  },
  {
    slug: 'drums',
    name: 'Drums & Percussion',
    blurb: 'Kits, snares, cymbals, hardware, and sticks by the handful.',
    plate: 'drums',
    weight: 'major',
    group: 'drums',
    image: {
      src: '/photos/demo/drums-1.jpg',
      alt: 'A drummer playing an orange-to-black sunburst drum kit — demo photography, not shop stock',
    },
  },
  {
    slug: 'band-instruments',
    name: 'Band & Orchestra',
    blurb: 'Student horns and strings, set up and serviced in house.',
    plate: 'band',
    weight: 'minor',
    group: 'band',
    image: {
      src: '/photos/demo/clarinet.jpg',
      alt: 'A black-body clarinet with silver keywork — demo photography, not shop stock',
    },
  },
  {
    slug: 'pro-audio',
    name: 'Pro Audio',
    blurb: 'Mixers, speakers, monitors, and everything that carries a room.',
    plate: 'pro-audio',
    weight: 'major',
    group: 'audio',
    image: {
      src: '/photos/demo/mixing-console.jpg',
      alt: 'A multi-channel analog mixing console in a studio — demo photography, not shop stock',
    },
  },
  {
    slug: 'microphones',
    name: 'Microphones',
    blurb: 'Stage workhorses and studio condensers.',
    plate: 'microphone',
    weight: 'minor',
    group: 'audio',
    image: {
      src: '/photos/demo/microphone-1.jpg',
      alt: 'Close-up of a handheld dynamic microphone head — demo photography, not shop stock',
    },
  },
  {
    slug: 'accessories',
    name: 'Accessories',
    blurb: 'Strings, cables, stands, reeds, sticks, straps, and cases.',
    plate: 'accessory',
    weight: 'minor',
    group: 'accessories',
    // No honest generic photo for this department turned up in the demo
    // fetch (only a branded gig bag) — left on the drawn plate rather than
    // reach for a mismatch. See HANDOFF.md.
    image: null,
  },
];

/* ------------------------------------------------------------------ */
/* Builder                                                             */
/* ------------------------------------------------------------------ */

/**
 * A seed entry. Only what actually varies is written out; everything else
 * takes a sensible default below, which is what keeps sixty products
 * readable instead of becoming sixty identical twenty-line blocks.
 */
interface Seed {
  sku: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  sub?: string;
  /** One sentence, for Quick View and search suggestions. */
  short: string;
  body: string;
  price: number;
  sale?: number;
  condition?: Product['condition'];
  stock?: number;
  plate: Product['plate'];
  alt: string;
  /** Path to verified demo photography for this exact product, or omitted to
   *  keep the drawn plate. Only set where the photo genuinely matches the
   *  brand/model/shape — see HANDOFF.md for the ones rejected as mismatches. */
  image?: string;
  /** `[label, value]` pairs — free-form, different per instrument family. */
  specs?: [string, string][];
  tags?: string[];
  arrived: string;
  featured?: boolean;
  isNew?: boolean;
  pick?: boolean;
  trade?: boolean;
  pickupOnly?: boolean;
  enquiry?: boolean;
}

function define(seed: Seed): Product {
  const specs: SpecEntry[] = (seed.specs ?? []).map(([label, value]) => ({ label, value }));
  const pickupOnly = seed.pickupOnly ?? false;

  return {
    // The stock number *is* the id. An id that is a position in this array
    // changes meaning whenever somebody reorders the file, which silently
    // repoints every saved cart and wishlist at the wrong instrument. A SKU
    // is the number on the tag and it does not move.
    id: seed.sku,
    sku: seed.sku,
    slug: seed.slug,
    name: seed.name,
    brand: seed.brand,
    category: seed.category,
    subcategory: seed.sub ?? null,
    shortDescription: seed.short,
    description: seed.body,
    price: seed.price,
    salePrice: seed.sale ?? null,
    condition: seed.condition ?? 'new',
    inventory: seed.stock ?? 3,
    pickupOnly,
    shippingAvailable: !pickupOnly,
    // One image per seed product: there is no real photography yet, and a
    // second identical drawn plate would be a hover effect that changes
    // nothing. Real second photographs go here and the card picks them up.
    images: [{ src: seed.image ?? null, alt: seed.alt }],
    plate: seed.plate,
    specifications: specs,
    tags: seed.tags ?? [],
    featured: seed.featured ?? false,
    newArrival: seed.isNew ?? false,
    staffPick: seed.pick ?? false,
    localTrade: seed.trade ?? false,
    arrivedAt: seed.arrived,
    ...(seed.enquiry ? { enquiryOnly: true } : {}),
  };
}

/* ------------------------------------------------------------------ */
/* Stock                                                               */
/* ------------------------------------------------------------------ */

export const products: Product[] = [
  /* ---- Electric guitars ------------------------------------------ */
  define({
    sku: 'QM-EG-1101',
    slug: 'fender-player-ii-stratocaster-black',
    name: 'Player II Stratocaster',
    brand: 'Fender',
    category: 'electric-guitars',
    sub: 'Solid body',
    short: 'The electric guitar most people picture when they picture an electric guitar.',
    body: 'The Stratocaster most people picture when they picture an electric guitar. Three single coils, a rolled fingerboard edge that feels broken in on day one, and a neck that suits almost everybody. A safe first electric and a guitar plenty of working players never bother to replace.',
    price: 89999,
    stock: 4,
    plate: 'electric-guitar',
    alt: 'Black Fender Player II Stratocaster electric guitar, front view',
    specs: [
      ['Body', 'Alder'],
      ['Neck', 'Maple, modern C'],
      ['Fingerboard', 'Rosewood, 9.5" radius'],
      ['Pickups', 'Three Player II single coils'],
      ['Bridge', '2-point synchronised tremolo'],
      ['Scale', '25.5"'],
      ['Finish', 'Black, gloss polyester'],
    ],
    tags: ['strat', 'single coil', 'beginner friendly'],
    arrived: '2026-07-02',
    featured: true,
  }),
  define({
    sku: 'QM-EG-1102',
    slug: 'gibson-les-paul-standard-50s-tobacco-burst',
    name: 'Les Paul Standard 50s',
    brand: 'Gibson',
    category: 'electric-guitars',
    sub: 'Solid body',
    short: 'Mahogany, maple, two humbuckers, and the fat fifties neck.',
    body: 'Mahogany body, maple cap, two humbuckers, and the fat neck profile the fifties originals are known for. Heavy in the best way. Come play it through something loud before you decide.',
    price: 279999,
    sale: 259999,
    stock: 1,
    plate: 'electric-guitar',
    alt: 'Gibson Les Paul Standard 50s in tobacco burst, front view',
    specs: [
      ['Body', 'Mahogany with maple top'],
      ['Neck', 'Mahogany, 50s vintage profile'],
      ['Fingerboard', 'Rosewood'],
      ['Pickups', 'Burstbucker 61R / 61T'],
      ['Finish', 'Tobacco burst, nitrocellulose'],
      ['Case', 'Hardshell included'],
    ],
    tags: ['humbucker', 'les paul', 'set neck'],
    arrived: '2026-06-18',
    featured: true,
    pick: true,
  }),
  define({
    sku: 'QM-EG-1103',
    slug: 'squier-classic-vibe-60s-telecaster',
    name: 'Classic Vibe 60s Telecaster',
    brand: 'Squier',
    category: 'electric-guitars',
    sub: 'Solid body',
    short: 'A genuinely good Telecaster for people who have not decided how much to spend.',
    body: 'The one we hand to people who have decided they want a Telecaster but have not decided how much to spend. Genuinely good out of the case, and we set every one up before it leaves the shop.',
    price: 46999,
    stock: 6,
    plate: 'electric-guitar',
    alt: 'Squier Classic Vibe 60s Telecaster, front view',
    specs: [
      ['Body', 'Nato'],
      ['Neck', 'Maple, slim C'],
      ['Pickups', 'Fender-designed alnico single coils'],
      ['Setup', 'Included, done in house'],
    ],
    tags: ['tele', 'twang', 'first electric'],
    arrived: '2026-05-30',
  }),
  define({
    sku: 'QM-EG-1104',
    slug: 'epiphone-es-335-figured',
    name: 'ES-335 Figured',
    brand: 'Epiphone',
    category: 'electric-guitars',
    sub: 'Semi-hollow',
    short: 'A semi-hollow that does blues, jazz, gospel and rock without complaining.',
    body: 'A semi-hollow with a maple centre block, which is what stops it howling when you turn up. Does blues, jazz, Sunday morning, and rock and roll without ever sounding like it is out of its depth.',
    price: 69999,
    stock: 2,
    plate: 'electric-guitar',
    alt: 'Epiphone ES-335 figured semi-hollow electric guitar',
    // Demo photography: a real cherry-red semi-hollow of this body style —
    // see public/photos/demo/CREDITS.json.
    image: '/photos/demo/semi-hollow-guitar.jpg',
    specs: [
      ['Body', 'Layered maple, centre block'],
      ['Neck', 'Mahogany, rounded C'],
      ['Pickups', 'Alnico Classic Pro humbuckers'],
      ['Hardware', 'LockTone bridge and tailpiece'],
    ],
    tags: ['semi hollow', '335', 'jazz'],
    arrived: '2026-08-21',
    isNew: true,
  }),
  define({
    sku: 'QM-EG-1105',
    slug: 'prs-se-custom-24',
    name: 'SE Custom 24',
    brand: 'PRS',
    category: 'electric-guitars',
    sub: 'Solid body',
    short: 'Twenty-four frets, coil splits, and a neck that suits shredders and strummers both.',
    body: 'Twenty-four frets, a tremolo that comes back in tune, and coil splits that make the humbuckers useful for more than one thing. It is the guitar we sell to players who own one electric and need it to cover everything.',
    price: 92900,
    stock: 3,
    plate: 'electric-guitar',
    alt: 'PRS SE Custom 24 electric guitar with figured maple top',
    specs: [
      ['Body', 'Mahogany with maple top'],
      ['Neck', 'Maple, wide thin'],
      ['Fingerboard', 'Rosewood, bird inlays'],
      ['Pickups', 'TCI S humbuckers with coil split'],
      ['Scale', '25"'],
    ],
    tags: ['versatile', 'coil split', 'tremolo'],
    arrived: '2026-08-04',
    isNew: true,
  }),
  define({
    sku: 'QM-EG-1106',
    slug: 'gretsch-g2622-streamliner-used',
    name: 'G2622 Streamliner',
    brand: 'Gretsch',
    category: 'electric-guitars',
    sub: 'Semi-hollow',
    short: 'Traded in by a player in town. Jangles like nothing else on the wall.',
    body: 'Came over the counter from a player here in town who was thinning out. Broad Tron pickups, a centre block, and a jangle you cannot get from anything else on the wall. Cleaned, fretted out, and set up on our bench.',
    price: 44999,
    sale: 39999,
    condition: 'used',
    stock: 1,
    plate: 'electric-guitar',
    alt: 'Used Gretsch G2622 Streamliner semi-hollow guitar',
    specs: [
      ['Body', 'Laminated maple'],
      ['Pickups', 'Broad Tron BT-2S'],
      ['Condition', 'Light finish checking on the lower bout'],
      ['Service', 'Fret polish, new strings, setup'],
    ],
    tags: ['jangle', 'trade in', 'semi hollow'],
    arrived: '2026-09-02',
    trade: true,
    pick: true,
  }),
  define({
    sku: 'QM-EG-1107',
    slug: 'ibanez-rg550-genesis',
    name: 'RG550 Genesis',
    brand: 'Ibanez',
    category: 'electric-guitars',
    sub: 'Solid body',
    short: 'A thin fast neck and a locking tremolo, built for people who play quickly.',
    body: 'Thin fast neck, jumbo frets, a locking tremolo that stays put, and a pickup layout that gets from clean to a wall of noise. If you play quickly, this is the one on the wall for you.',
    price: 119999,
    stock: 2,
    plate: 'electric-guitar',
    alt: 'Ibanez RG550 Genesis electric guitar in desert yellow',
    specs: [
      ['Body', 'Basswood'],
      ['Neck', 'Maple, Super Wizard'],
      ['Frets', '24 jumbo'],
      ['Bridge', 'Edge locking tremolo'],
    ],
    tags: ['shred', 'floyd', 'fast neck'],
    arrived: '2026-04-11',
  }),
  define({
    sku: 'QM-EG-1108',
    slug: 'fender-squier-sonic-stratocaster-pack',
    name: 'Sonic Stratocaster Starter Pack',
    brand: 'Squier',
    category: 'electric-guitars',
    sub: 'Starter pack',
    short: 'Guitar, amp, strap, lead and tuner — everything a first player needs.',
    body: 'Guitar, small amp, strap, lead, picks and a tuner, all in one box, and set up by us before it goes home. The honest way to find out whether somebody is going to stick with it.',
    price: 32999,
    sale: 27999,
    stock: 7,
    plate: 'electric-guitar',
    alt: 'Squier Sonic Stratocaster starter pack with practice amplifier',
    specs: [
      ['Included', 'Guitar, 10W amp, strap, cable, picks, tuner'],
      ['Setup', 'Included, done in house'],
      ['Best for', 'A first electric guitar'],
    ],
    tags: ['starter', 'gift', 'bundle', 'beginner'],
    arrived: '2026-07-19',
  }),

  /* ---- Acoustic guitars ------------------------------------------ */
  define({
    sku: 'QM-AG-2101',
    slug: 'martin-d-10e-road-series',
    name: 'D-10E Road Series',
    brand: 'Martin',
    category: 'acoustic-guitars',
    sub: 'Dreadnought',
    short: 'A real Martin dreadnought, with a pickup already fitted.',
    body: 'Solid sitka top, solid sapele back and sides, and a pickup already in it. A real Martin dreadnought at a price that makes sense for somebody who plays out on Sundays.',
    price: 119999,
    stock: 2,
    plate: 'acoustic-guitar',
    alt: 'Martin D-10E Road Series dreadnought acoustic guitar',
    specs: [
      ['Top', 'Solid sitka spruce'],
      ['Back & sides', 'Solid sapele'],
      ['Neck', 'Select hardwood, performing artist profile'],
      ['Electronics', 'Fishman MX-T'],
      ['Case', 'Softshell included'],
    ],
    tags: ['dreadnought', 'electro acoustic', 'worship'],
    arrived: '2026-06-02',
    featured: true,
  }),
  define({
    sku: 'QM-AG-2102',
    slug: 'yamaha-fg800-natural',
    name: 'FG800',
    brand: 'Yamaha',
    category: 'acoustic-guitars',
    sub: 'Dreadnought',
    short: 'The guitar we have put in more first-time hands than any other.',
    body: 'The first guitar we have put in more hands than any other. Solid spruce top, sensible price, and it stays playable. If a parent asks us what to start a twelve year old on, this is usually the answer.',
    price: 23999,
    sale: 19999,
    stock: 9,
    plate: 'acoustic-guitar',
    alt: 'Yamaha FG800 natural finish acoustic guitar',
    specs: [
      ['Top', 'Solid spruce'],
      ['Back & sides', 'Nato'],
      ['Nut width', '43 mm'],
      ['Setup', 'Included, done in house'],
    ],
    tags: ['beginner', 'value', 'first guitar'],
    arrived: '2026-05-14',
    featured: true,
  }),
  define({
    sku: 'QM-AG-2103',
    slug: 'taylor-gs-mini-mahogany',
    name: 'GS Mini Mahogany',
    brand: 'Taylor',
    category: 'acoustic-guitars',
    sub: 'Travel',
    short: 'Small body, full sound, and the guitar most likely to get picked up.',
    body: 'Small body, full sound, and the guitar most likely to actually get picked up off the couch. Hard to put down once you have played one.',
    price: 76999,
    stock: 2,
    plate: 'acoustic-guitar',
    alt: 'Taylor GS Mini with mahogany top',
    specs: [
      ['Top', 'Solid mahogany'],
      ['Back & sides', 'Layered sapele'],
      ['Scale', '23.5"'],
      ['Case', 'Structured gig bag'],
    ],
    tags: ['travel', 'small body', 'couch guitar'],
    arrived: '2026-08-12',
    isNew: true,
    pick: true,
  }),
  define({
    sku: 'QM-AG-2104',
    slug: 'gibson-j-45-standard',
    name: 'J-45 Standard',
    brand: 'Gibson',
    category: 'acoustic-guitars',
    sub: 'Round shoulder',
    short: 'The round-shouldered workhorse that sits under a singing voice perfectly.',
    body: 'The round-shouldered slope that has sat under more singing voices than any other guitar. Warm, a little woody, and it never fights the person holding it. We keep one here to be played.',
    price: 329900,
    stock: 1,
    plate: 'acoustic-guitar',
    alt: 'Gibson J-45 Standard acoustic guitar in vintage sunburst',
    specs: [
      ['Top', 'Sitka spruce'],
      ['Back & sides', 'Mahogany'],
      ['Neck', 'Mahogany, round profile'],
      ['Electronics', 'LR Baggs VTC'],
      ['Case', 'Hardshell included'],
    ],
    tags: ['singer songwriter', 'slope shoulder'],
    arrived: '2026-03-27',
    featured: true,
  }),
  define({
    sku: 'QM-AG-2105',
    slug: 'seagull-s6-original-used',
    name: 'S6 Original',
    brand: 'Seagull',
    category: 'acoustic-guitars',
    sub: 'Dreadnought',
    short: 'A Canadian-built cedar-top traded in locally, and better for the miles.',
    body: 'Canadian-built, cedar top, wide nut. Traded in by somebody local who had played it for fifteen years, which is exactly how long it takes a cedar top to get good. Set up and restrung here.',
    price: 34999,
    condition: 'used',
    stock: 1,
    plate: 'acoustic-guitar',
    alt: 'Used Seagull S6 Original acoustic guitar with cedar top',
    specs: [
      ['Top', 'Solid cedar, pressure tested'],
      ['Nut width', '1.8"'],
      ['Condition', 'Pick wear below the soundhole, no cracks'],
      ['Service', 'Setup and new strings'],
    ],
    tags: ['cedar', 'trade in', 'wide nut'],
    arrived: '2026-08-29',
    trade: true,
  }),
  define({
    sku: 'QM-AG-2106',
    slug: 'fender-cd-60sce-all-mahogany',
    name: 'CD-60SCE All-Mahogany',
    brand: 'Fender',
    category: 'acoustic-guitars',
    sub: 'Cutaway',
    short: 'A cutaway electro-acoustic that does not cost what one usually costs.',
    body: 'Cutaway, pickup, tuner built in, and a mahogany top that sounds warmer than the price suggests. A sensible first guitar for somebody who already knows they will be plugging in.',
    price: 29999,
    stock: 4,
    plate: 'acoustic-guitar',
    alt: 'Fender CD-60SCE all-mahogany cutaway acoustic electric guitar',
    specs: [
      ['Top', 'Solid mahogany'],
      ['Electronics', 'Fishman preamp with tuner'],
      ['Neck', 'Mahogany, easy-to-play C'],
    ],
    tags: ['cutaway', 'electro acoustic', 'value'],
    arrived: '2026-07-08',
  }),
  define({
    sku: 'QM-AG-2107',
    slug: 'guild-p-240-memoir-parlour',
    name: 'P-240 Memoir Parlour',
    brand: 'Guild',
    category: 'acoustic-guitars',
    sub: 'Parlour',
    short: 'A small-bodied parlour with far more voice than its size suggests.',
    body: 'A parlour guitar with a proper voice — tight, focused, and loud enough to surprise people. Sits well under a microphone and well in a small room.',
    price: 84999,
    stock: 1,
    plate: 'acoustic-guitar',
    alt: 'Guild P-240 Memoir parlour acoustic guitar',
    specs: [
      ['Top', 'Solid sitka spruce'],
      ['Back & sides', 'Solid mahogany'],
      ['Scale', '24.75"'],
      ['Finish', 'Natural, satin nitro'],
    ],
    tags: ['parlour', 'small body', 'fingerstyle'],
    arrived: '2026-08-26',
    isNew: true,
  }),

  /* ---- Classical & ukulele --------------------------------------- */
  define({
    sku: 'QM-CG-2201',
    slug: 'cordoba-c5-classical',
    name: 'C5 Classical',
    brand: 'Cordoba',
    category: 'classical-guitars',
    sub: 'Full size',
    short: 'A full-size nylon string for lessons, exams, and quiet houses.',
    body: 'Solid cedar top, nylon strings, and a neck wide enough to do classical technique properly. The one we sell to students working through a syllabus.',
    price: 39999,
    stock: 3,
    plate: 'acoustic-guitar',
    alt: 'Cordoba C5 solid-top classical nylon string guitar',
    // Demo photography: a real classical guitar of this style — see
    // public/photos/demo/CREDITS.json.
    image: '/photos/demo/classical-guitar.jpg',
    specs: [
      ['Top', 'Solid Canadian cedar'],
      ['Back & sides', 'Mahogany'],
      ['Nut width', '52 mm'],
      ['Strings', 'Nylon'],
    ],
    tags: ['nylon', 'classical', 'student'],
    arrived: '2026-06-24',
  }),
  define({
    sku: 'QM-CG-2202',
    slug: 'yamaha-cgs103a-three-quarter',
    name: 'CGS103A 3/4 Classical',
    brand: 'Yamaha',
    category: 'classical-guitars',
    sub: 'Three-quarter size',
    short: 'A three-quarter nylon string sized for younger hands.',
    body: 'A three-quarter size nylon string for smaller hands. Nylon is easier on fingers that have never had calluses, which is why most teachers around here start children on one.',
    price: 17999,
    stock: 5,
    plate: 'acoustic-guitar',
    alt: 'Yamaha CGS103A three-quarter size classical guitar',
    specs: [
      ['Scale', '23.6"'],
      ['Top', 'Spruce'],
      ['Best for', 'Ages 8 to 12'],
    ],
    tags: ['child', 'nylon', 'lessons'],
    arrived: '2026-05-05',
  }),
  define({
    sku: 'QM-UK-2301',
    slug: 'kala-ka-15s-soprano',
    name: 'KA-15S Soprano Ukulele',
    brand: 'Kala',
    category: 'ukuleles',
    sub: 'Soprano',
    short: 'The standard first ukulele, set up properly before it leaves.',
    body: 'Mahogany, satin finish, and set up here so it plays in tune past the fifth fret — which is more than can be said for most ukuleles at this price.',
    price: 8999,
    stock: 8,
    plate: 'acoustic-guitar',
    alt: 'Kala KA-15S mahogany soprano ukulele',
    specs: [
      ['Body', 'Mahogany'],
      ['Scale', '13.625"'],
      ['Setup', 'Included, done in house'],
    ],
    tags: ['uke', 'gift', 'beginner'],
    arrived: '2026-07-29',
  }),
  define({
    sku: 'QM-UK-2302',
    slug: 'kala-ka-scg-concert',
    name: 'KA-SCG Concert Ukulele',
    brand: 'Kala',
    category: 'ukuleles',
    sub: 'Concert',
    short: 'A concert-scale solid-top uke with room for adult hands.',
    body: 'A step up in size and in voice: solid spruce top, concert scale, and enough room between the frets for adult hands.',
    price: 16999,
    stock: 3,
    plate: 'acoustic-guitar',
    alt: 'Kala KA-SCG solid spruce concert ukulele',
    specs: [
      ['Top', 'Solid spruce'],
      ['Scale', '15"'],
      ['Tuners', 'Chrome die-cast'],
    ],
    tags: ['uke', 'concert', 'solid top'],
    arrived: '2026-08-18',
    isNew: true,
  }),

  /* ---- Bass ------------------------------------------------------- */
  define({
    sku: 'QM-BG-3101',
    slug: 'fender-player-ii-precision-bass',
    name: 'Player II Precision Bass',
    brand: 'Fender',
    category: 'bass',
    sub: 'Electric bass',
    short: 'The bass that sits in a mix without arguing with anything.',
    body: 'The bass that sits in the mix without arguing. Split-coil pickup, familiar neck, and it works for country, gospel, rock, and everything played in a church on Sunday morning.',
    price: 89999,
    stock: 2,
    plate: 'bass',
    alt: 'Fender Player II Precision Bass, front view',
    specs: [
      ['Body', 'Alder'],
      ['Neck', 'Maple, modern C'],
      ['Pickup', 'Split single coil'],
      ['Scale', '34"'],
    ],
    tags: ['p bass', 'worship', 'session'],
    arrived: '2026-06-09',
  }),
  define({
    sku: 'QM-BG-3102',
    slug: 'ibanez-sr300e-used',
    name: 'SR300E',
    brand: 'Ibanez',
    category: 'bass',
    sub: 'Electric bass',
    short: 'A traded-in step up from a starter bass, cleaned and set up.',
    body: 'Traded in and cleaned up. Thin fast neck, active preamp, light body. A good step up from a starter bass without spending like it.',
    price: 32999,
    condition: 'used',
    stock: 1,
    plate: 'bass',
    alt: 'Used Ibanez SR300E electric bass guitar',
    specs: [
      ['Preamp', 'Ibanez Custom 3-band'],
      ['Scale', '34"'],
      ['Condition', 'Light buckle wear on the back'],
      ['Service', 'Fresh strings and setup'],
    ],
    tags: ['trade in', 'active', 'slim neck'],
    arrived: '2026-09-05',
    trade: true,
  }),
  define({
    sku: 'QM-BG-3103',
    slug: 'sterling-stingray-ray34',
    name: 'StingRay RAY34',
    brand: 'Sterling by Music Man',
    category: 'bass',
    sub: 'Electric bass',
    short: 'A humbucker in the sweet spot and a preamp that pushes a room.',
    body: 'One big humbucker in exactly the right place and an active preamp behind it. Cuts through a loud band without needing to be turned up, which is the whole trick.',
    price: 84999,
    stock: 2,
    plate: 'bass',
    alt: 'Sterling by Music Man StingRay RAY34 bass guitar',
    specs: [
      ['Body', 'Ash'],
      ['Pickup', 'Ceramic humbucker'],
      ['Preamp', 'Active 3-band'],
      ['Bridge', 'Vintage-style top-load'],
    ],
    tags: ['stingray', 'funk', 'active'],
    arrived: '2026-08-07',
    isNew: true,
  }),
  define({
    sku: 'QM-BG-3104',
    slug: 'squier-affinity-jazz-bass',
    name: 'Affinity Jazz Bass',
    brand: 'Squier',
    category: 'bass',
    sub: 'Electric bass',
    short: 'A narrow-necked first bass that is easy to get around.',
    body: 'Two pickups, a narrow neck, and a body that does not weigh anything. The bass most of our first-time players leave with, and it takes a setup well.',
    price: 27999,
    stock: 5,
    plate: 'bass',
    alt: 'Squier Affinity Jazz Bass in black',
    // Demo photography: a real Jazz Bass of this body style, different
    // finish — see public/photos/demo/CREDITS.json.
    image: '/photos/demo/bass-guitar-2.jpg',
    specs: [
      ['Neck', 'Maple, slim C'],
      ['Pickups', 'Two single coils'],
      ['Setup', 'Included, done in house'],
    ],
    tags: ['jazz bass', 'beginner', 'value'],
    arrived: '2026-04-30',
  }),
  define({
    sku: 'QM-BG-3105',
    slug: 'ampeg-rocket-bass-ra110',
    name: 'Rocket Bass RB-110',
    brand: 'Ampeg',
    category: 'bass',
    sub: 'Bass amplifier',
    short: 'A 50-watt practice bass combo that still sounds like Ampeg.',
    body: 'Fifty watts and a ten inch speaker: enough for a bedroom, a lesson room, or a quiet rehearsal. Still has the Ampeg growl when you push the gain.',
    price: 29999,
    stock: 3,
    plate: 'amplifier',
    alt: 'Ampeg Rocket Bass RB-110 combo amplifier',
    specs: [
      ['Power', '50 watts'],
      ['Speaker', '10" custom'],
      ['Features', 'Super Grit overdrive, headphone out'],
    ],
    tags: ['practice amp', 'bass amp'],
    arrived: '2026-06-15',
  }),

  /* ---- Amplifiers ------------------------------------------------- */
  define({
    sku: 'QM-AMP-4101',
    slug: 'used-1978-fender-twin-reverb',
    name: '1978 Twin Reverb',
    brand: 'Fender',
    category: 'amplifiers',
    sub: 'Tube combo',
    short: 'A serviced silverface Twin. Loud, heavy, and it sounds like a record.',
    body: 'A silverface Twin that came to us from a player two counties over. Serviced on the bench here: new filter caps, biased, jacks cleaned, original transformers and speakers. It is loud, it is heavy, and it sounds like a record. One only.',
    price: 179999,
    condition: 'vintage',
    stock: 1,
    plate: 'amplifier',
    alt: 'Silverface Fender Twin Reverb combo amplifier from 1978',
    specs: [
      ['Power', '135 watts'],
      ['Speakers', '2 x 12" original'],
      ['Tubes', '6L6GC power section'],
      ['Service', 'Recapped and biased in our shop'],
      ['Cosmetics', 'Honest wear, tolex intact'],
      ['Serial', 'Available on request'],
    ],
    tags: ['vintage', 'silverface', 'clean headroom'],
    arrived: '2026-07-24',
    featured: true,
    pickupOnly: true,
    enquiry: true,
    trade: true,
  }),
  define({
    sku: 'QM-AMP-4102',
    slug: 'fender-blues-junior-iv',
    name: 'Blues Junior IV',
    brand: 'Fender',
    category: 'amplifiers',
    sub: 'Tube combo',
    short: 'Fifteen watts with just enough headroom for a small room.',
    body: 'Fifteen watts, one twelve, and enough headroom for a small room before it starts to break up. The amp we sell most often to people playing worship services and bar gigs alike.',
    price: 79999,
    stock: 3,
    plate: 'amplifier',
    alt: 'Fender Blues Junior IV tube combo amplifier',
    specs: [
      ['Power', '15 watts'],
      ['Speaker', '12" Celestion A-Type'],
      ['Tubes', 'EL84 power section'],
      ['Reverb', 'Spring'],
    ],
    tags: ['tube', 'gigging', 'combo'],
    arrived: '2026-05-21',
  }),
  define({
    sku: 'QM-AMP-4103',
    slug: 'vox-ac15c1',
    name: 'AC15C1',
    brand: 'Vox',
    category: 'amplifiers',
    sub: 'Tube combo',
    short: 'Chime at low volume, grind when pushed — the classic British combo.',
    body: 'The British chime, at a volume you can actually use. Fifteen watts through a Greenback, top boost when you want it to get sharp, and tremolo and reverb built in.',
    price: 89999,
    stock: 2,
    plate: 'amplifier',
    alt: 'Vox AC15C1 tube combo amplifier in black',
    specs: [
      ['Power', '15 watts'],
      ['Speaker', '12" Celestion G12M Greenback'],
      ['Channels', 'Normal and Top Boost'],
      ['Effects', 'Spring reverb and tremolo'],
    ],
    tags: ['chime', 'british', 'tube'],
    arrived: '2026-08-14',
    isNew: true,
  }),
  define({
    sku: 'QM-AMP-4104',
    slug: 'boss-katana-100-mkii',
    name: 'Katana-100 MkII',
    brand: 'Boss',
    category: 'amplifiers',
    sub: 'Modelling combo',
    short: 'Five amp voices and sixty effects for players with one amp and many bands.',
    body: 'Five amp voices, a pile of Boss effects built in, and a power control that lets you get the same sound at half a watt. The practical answer for someone playing in more than one band.',
    price: 42999,
    sale: 37999,
    stock: 4,
    plate: 'amplifier',
    alt: 'Boss Katana-100 MkII modelling guitar amplifier',
    specs: [
      ['Power', '100 watts, switchable to 50 / 0.5'],
      ['Speaker', '12" custom'],
      ['Effects', '60 Boss effects, five simultaneous'],
      ['Recording', 'USB out'],
    ],
    tags: ['modelling', 'versatile', 'home recording'],
    arrived: '2026-07-11',
  }),
  define({
    sku: 'QM-AMP-4105',
    slug: 'orange-crush-20',
    name: 'Crush 20',
    brand: 'Orange',
    category: 'amplifiers',
    sub: 'Practice combo',
    short: 'A twenty-watt practice amp that is genuinely fun at low volume.',
    body: 'Twenty watts, two channels, and a headphone output with cabinet simulation so it can be played at two in the morning. It is also orange, which nobody has ever complained about.',
    price: 17999,
    stock: 6,
    plate: 'amplifier',
    alt: 'Orange Crush 20 practice guitar amplifier',
    specs: [
      ['Power', '20 watts'],
      ['Speaker', '8" Voice of the World'],
      ['Outputs', 'Headphone with CabSim'],
    ],
    tags: ['practice', 'bedroom', 'headphones'],
    arrived: '2026-06-28',
  }),
  define({
    sku: 'QM-AMP-4106',
    slug: 'roland-ac-33-acoustic-amp',
    name: 'AC-33 Acoustic Chorus',
    brand: 'Roland',
    category: 'amplifiers',
    sub: 'Acoustic amplifier',
    short: 'A battery-powered acoustic amp for buskers and coffee-shop gigs.',
    body: 'Thirty watts, runs on batteries, and has a microphone channel as well as an instrument one. Built for the gig in the corner of a coffee shop where there is no power outlet.',
    price: 49999,
    stock: 2,
    plate: 'amplifier',
    alt: 'Roland AC-33 battery powered acoustic amplifier',
    specs: [
      ['Power', '30 watts stereo'],
      ['Power source', 'Mains or eight AA batteries'],
      ['Channels', 'Guitar and microphone'],
      ['Effects', 'Chorus, reverb, looper'],
    ],
    tags: ['acoustic', 'busking', 'battery'],
    arrived: '2026-05-08',
  }),

  /* ---- Pedals ----------------------------------------------------- */
  define({
    sku: 'QM-PDL-4201',
    slug: 'boss-ds-1-distortion',
    name: 'DS-1 Distortion',
    brand: 'Boss',
    category: 'pedals',
    sub: 'Distortion',
    short: 'Orange, indestructible, and on more pedalboards than anything else.',
    body: 'Orange, indestructible, and on more pedalboards than anything else ever made. Still the cheapest way to find out whether you like distortion.',
    price: 6499,
    stock: 12,
    plate: 'pedal',
    alt: 'Boss DS-1 orange distortion pedal',
    specs: [
      ['Controls', 'Tone, Level, Distortion'],
      ['Power', '9V adaptor or battery'],
      ['Bypass', 'Buffered'],
    ],
    tags: ['dirt', 'classic', 'first pedal'],
    arrived: '2026-04-16',
  }),
  define({
    sku: 'QM-PDL-4202',
    slug: 'strymon-flint-reverb-tremolo',
    name: 'Flint Reverb & Tremolo',
    brand: 'Strymon',
    category: 'pedals',
    sub: 'Reverb',
    short: 'Three reverbs and three tremolos in one box, all of them good.',
    body: 'Three reverbs and three tremolos in one box, all of them good. If you are chasing the sound of an old amp without hauling an old amp, start here.',
    price: 37900,
    stock: 2,
    plate: 'pedal',
    alt: 'Strymon Flint reverb and tremolo pedal',
    specs: [
      ['Reverbs', "60s spring, 70s plate, 80s hall"],
      ['Tremolos', '61 harmonic, 63 power tube, 65 photocell'],
      ['Bypass', 'True or buffered'],
    ],
    tags: ['ambient', 'boutique', 'studio'],
    arrived: '2026-07-05',
    pick: true,
  }),
  define({
    sku: 'QM-PDL-4203',
    slug: 'ibanez-ts9-tube-screamer',
    name: 'TS9 Tube Screamer',
    brand: 'Ibanez',
    category: 'pedals',
    sub: 'Overdrive',
    short: 'The green box that pushes an amp into the good part of its range.',
    body: 'The green box. It does not do much on its own — it pushes an already-driven amp into the part of its range you actually wanted, and that mid hump is the whole point.',
    price: 11999,
    stock: 5,
    plate: 'pedal',
    alt: 'Ibanez TS9 Tube Screamer overdrive pedal',
    // Demo photography: a real Ibanez Tube Screamer — see
    // public/photos/demo/CREDITS.json.
    image: '/photos/demo/pedal-1.jpg',
    specs: [
      ['Controls', 'Drive, Tone, Level'],
      ['Power', '9V adaptor or battery'],
    ],
    tags: ['overdrive', 'blues', 'mid hump'],
    arrived: '2026-06-11',
  }),
  define({
    sku: 'QM-PDL-4204',
    slug: 'electro-harmonix-big-muff-pi',
    name: 'Big Muff Pi',
    brand: 'Electro-Harmonix',
    category: 'pedals',
    sub: 'Fuzz',
    short: 'Enormous fuzz with an endless sustain, for when subtlety is not wanted.',
    body: 'Enormous, woolly fuzz with sustain that goes on until you stop it. Not a subtle pedal and has never pretended to be.',
    price: 10999,
    stock: 4,
    plate: 'pedal',
    alt: 'Electro-Harmonix Big Muff Pi fuzz pedal',
    specs: [
      ['Controls', 'Volume, Tone, Sustain'],
      ['Power', '9V adaptor or battery'],
    ],
    tags: ['fuzz', 'sustain', 'stoner'],
    arrived: '2026-05-26',
  }),
  define({
    sku: 'QM-PDL-4205',
    slug: 'tc-electronic-polytune-3',
    name: 'PolyTune 3',
    brand: 'TC Electronic',
    category: 'pedals',
    sub: 'Tuner',
    short: 'Strum all six strings and see every one of them at once.',
    body: 'Strum all six strings and it shows you every one at once, which saves about a minute per song on stage. There is a buffer in it too, which most boards need.',
    price: 10999,
    stock: 7,
    plate: 'pedal',
    alt: 'TC Electronic PolyTune 3 polyphonic tuner pedal',
    specs: [
      ['Accuracy', '+/- 0.02 cents in strobe mode'],
      ['Buffer', 'Bonafide buffer, switchable'],
    ],
    tags: ['tuner', 'utility', 'buffer'],
    arrived: '2026-08-20',
    isNew: true,
  }),
  define({
    sku: 'QM-PDL-4206',
    slug: 'walrus-audio-slo-reverb',
    name: 'Slö Multi-Texture Reverb',
    brand: 'Walrus Audio',
    category: 'pedals',
    sub: 'Reverb',
    short: 'Three ambient reverbs for the part of the set where nobody sings.',
    body: 'Three ambient reverb programmes with modulation built in — dark, rise and dream. Built for the part of the set where nothing is being sung.',
    price: 29900,
    stock: 1,
    plate: 'pedal',
    alt: 'Walrus Audio Slö multi-texture reverb pedal',
    specs: [
      ['Programmes', 'Dark, Rise, Dream'],
      ['Controls', 'Decay, Filter, Mix, X, D/S'],
      ['Bypass', 'True bypass with trails option'],
    ],
    tags: ['ambient', 'worship', 'shoegaze'],
    arrived: '2026-09-01',
    isNew: true,
  }),

  /* ---- Keyboards -------------------------------------------------- */
  define({
    sku: 'QM-KEY-5101',
    slug: 'yamaha-p-145-digital-piano',
    name: 'P-145 Digital Piano',
    brand: 'Yamaha',
    category: 'keyboards',
    sub: 'Digital piano',
    short: 'Eighty-eight weighted keys in something one person can carry.',
    body: 'Eighty-eight weighted keys in something one person can carry. The keyboard we recommend for lessons at home when an upright will not fit.',
    price: 59999,
    stock: 3,
    plate: 'keyboard',
    alt: 'Yamaha P-145 88-key digital piano',
    specs: [
      ['Keys', '88, Graded Hammer Compact'],
      ['Voices', '10'],
      ['Weight', '11.1 kg'],
      ['Outputs', 'Headphone, USB to host'],
    ],
    tags: ['lessons', 'weighted', 'portable'],
    arrived: '2026-06-05',
    featured: true,
  }),
  define({
    sku: 'QM-KEY-5102',
    slug: 'nord-stage-4-73',
    name: 'Stage 4 73',
    brand: 'Nord',
    category: 'keyboards',
    sub: 'Stage keyboard',
    short: 'The red one. If you play keys for a living you already know why.',
    body: 'The red one. If you play keys on a stage for a living you already know why. We keep one here to play, and we will order the configuration you want.',
    price: 499900,
    stock: 1,
    plate: 'keyboard',
    alt: 'Nord Stage 4 73-key stage keyboard',
    specs: [
      ['Keys', '73, waterfall'],
      ['Sections', 'Piano, Organ, Synth'],
      ['Availability', 'Floor model, special order'],
    ],
    tags: ['stage', 'session', 'flagship'],
    arrived: '2026-03-14',
    pickupOnly: true,
    enquiry: true,
  }),
  define({
    sku: 'QM-KEY-5103',
    slug: 'roland-fp-30x-digital-piano',
    name: 'FP-30X Digital Piano',
    brand: 'Roland',
    category: 'keyboards',
    sub: 'Digital piano',
    short: 'A weighted digital piano with speakers loud enough for a small room.',
    body: 'A properly weighted action and speakers with enough behind them to fill a small room without an amplifier. Bluetooth for playing along with whatever is on a phone.',
    price: 79999,
    stock: 2,
    plate: 'keyboard',
    alt: 'Roland FP-30X digital piano in black',
    specs: [
      ['Keys', '88, PHA-4 Standard with escapement'],
      ['Sound', 'SuperNATURAL piano'],
      ['Amplification', '22 W stereo'],
      ['Connectivity', 'Bluetooth audio and MIDI'],
    ],
    tags: ['weighted', 'home', 'bluetooth'],
    arrived: '2026-08-09',
    isNew: true,
  }),
  define({
    sku: 'QM-KEY-5104',
    slug: 'casio-ct-s1-portable-keyboard',
    name: 'CT-S1 Portable Keyboard',
    brand: 'Casio',
    category: 'keyboards',
    sub: 'Portable keyboard',
    short: 'Sixty-one keys, battery powered, and genuinely good speakers.',
    body: 'Sixty-one touch-sensitive keys, runs on batteries, and the speakers are surprisingly good. A sensible first keyboard that does not look like a toy.',
    price: 27999,
    sale: 23999,
    stock: 4,
    plate: 'keyboard',
    alt: 'Casio CT-S1 61-key portable keyboard',
    specs: [
      ['Keys', '61, touch sensitive'],
      ['Tones', '61'],
      ['Power', 'Mains or six AA batteries'],
    ],
    tags: ['portable', 'beginner', 'battery'],
    arrived: '2026-07-16',
  }),
  define({
    sku: 'QM-KEY-5105',
    slug: 'hammond-sk-pro-73',
    name: 'SK Pro 73',
    brand: 'Hammond',
    category: 'keyboards',
    sub: 'Stage organ',
    short: 'Drawbars, a real Leslie simulation, and pianos on top.',
    body: 'Nine drawbars, a Leslie simulation that holds up in a room, and acoustic and electric pianos stacked behind it. For the player who has to cover the organ part properly.',
    price: 289900,
    stock: 1,
    plate: 'keyboard',
    alt: 'Hammond SK Pro 73 stage organ keyboard',
    specs: [
      ['Keys', '73, waterfall'],
      ['Drawbars', 'Nine, physical'],
      ['Rotary', 'Digital Leslie simulation'],
    ],
    tags: ['organ', 'drawbars', 'gospel'],
    arrived: '2026-04-22',
    pickupOnly: true,
    enquiry: true,
  }),

  /* ---- Drums ------------------------------------------------------ */
  define({
    sku: 'QM-DRM-6101',
    slug: 'pearl-export-exx-5-piece',
    name: 'Export EXX 5-Piece Kit',
    brand: 'Pearl',
    category: 'drums',
    sub: 'Drum kit',
    short: 'The kit that has started more drummers than any other.',
    body: 'The kit that has started more drummers than any other. Comes with hardware and cymbals, and we will put it together with you so it goes home tuned.',
    price: 89999,
    sale: 79999,
    stock: 2,
    plate: 'drums',
    alt: 'Pearl Export EXX five-piece drum kit with cymbals',
    specs: [
      ['Shells', 'Poplar and Asian mahogany'],
      ['Configuration', '22" kick, 10"/12" toms, 16" floor, 14" snare'],
      ['Included', 'Hardware pack and cymbals'],
      ['Assembly', 'Built and tuned with you in store'],
    ],
    tags: ['first kit', 'bundle', 'student'],
    arrived: '2026-06-20',
    featured: true,
    pickupOnly: true,
  }),
  define({
    sku: 'QM-DRM-6102',
    slug: 'zildjian-a-custom-crash-18',
    name: 'A Custom Crash 18"',
    brand: 'Zildjian',
    category: 'drums',
    sub: 'Cymbal',
    short: 'Bright, fast, and it gets out of the way.',
    body: 'Bright, fast, and it gets out of the way. Come hit it before you buy it — that is the whole reason we keep cymbals on a stand instead of in a box.',
    price: 38999,
    stock: 4,
    plate: 'drums',
    alt: 'Zildjian A Custom 18 inch crash cymbal',
    specs: [
      ['Size', '18"'],
      ['Finish', 'Brilliant'],
      ['Weight', 'Thin'],
    ],
    tags: ['crash', 'bright', 'cymbal'],
    arrived: '2026-05-18',
  }),
  define({
    sku: 'QM-DRM-6103',
    slug: 'ludwig-supraphonic-lm400-snare',
    name: 'Supraphonic LM400 Snare',
    brand: 'Ludwig',
    category: 'drums',
    sub: 'Snare drum',
    short: 'The aluminium snare on more records than any other drum.',
    body: 'The aluminium snare that is on more records than any other drum ever made. Crack at the top, body underneath, and it sits in a mix without any help.',
    price: 47999,
    stock: 2,
    plate: 'drums',
    alt: 'Ludwig Supraphonic LM400 aluminium snare drum',
    specs: [
      ['Shell', 'Ludalloy aluminium'],
      ['Size', '14" x 5"'],
      ['Hoops', 'Triple flanged'],
    ],
    tags: ['snare', 'studio', 'classic'],
    arrived: '2026-08-16',
    isNew: true,
    pick: true,
  }),
  define({
    sku: 'QM-DRM-6104',
    slug: 'roland-td-07kv-electronic-kit',
    name: 'TD-07KV Electronic Kit',
    brand: 'Roland',
    category: 'drums',
    sub: 'Electronic kit',
    short: 'A mesh-head electronic kit quiet enough to practise on at night.',
    body: 'Mesh heads, so it feels enough like a drum to practise on properly, and quiet enough that the rest of the house will tolerate it. The answer for apartment drummers.',
    price: 84999,
    stock: 2,
    plate: 'drums',
    alt: 'Roland TD-07KV electronic drum kit with mesh heads',
    specs: [
      ['Heads', 'Dual-ply mesh, tunable'],
      ['Kits', '25 preset'],
      ['Connectivity', 'Bluetooth audio and MIDI'],
    ],
    tags: ['electronic', 'quiet practice', 'apartment'],
    arrived: '2026-07-26',
    pickupOnly: true,
  }),
  define({
    sku: 'QM-DRM-6105',
    slug: 'vic-firth-5a-sticks',
    name: '5A Drumsticks',
    brand: 'Vic Firth',
    category: 'drums',
    sub: 'Sticks',
    short: 'The default stick. We sell them by the handful.',
    body: 'The default stick, and the one most drummers come back to. Hickory, wood tip. We keep a bucket of them on the counter.',
    price: 1499,
    stock: 60,
    plate: 'drums',
    alt: 'Pair of Vic Firth American Classic 5A hickory drumsticks',
    specs: [
      ['Material', 'American hickory'],
      ['Tip', 'Wood, teardrop'],
      ['Diameter', '0.565"'],
    ],
    tags: ['sticks', 'consumable', 'hickory'],
    arrived: '2026-04-02',
  }),
  define({
    sku: 'QM-DRM-6106',
    slug: 'meinl-hcs-cymbal-set-used',
    name: 'HCS Cymbal Set',
    brand: 'Meinl',
    category: 'drums',
    sub: 'Cymbal',
    short: 'A traded-in student cymbal pack, cleaned and honest about its dings.',
    body: 'Hi-hats, a crash and a ride, traded in when a student upgraded. Cleaned up, no cracks, a couple of honest edge dings noted below. A cheap way to get a kit playable.',
    price: 17999,
    sale: 13999,
    condition: 'used',
    stock: 1,
    plate: 'drums',
    alt: 'Used Meinl HCS cymbal set with hi-hats, crash and ride',
    specs: [
      ['Included', '14" hi-hats, 16" crash, 20" ride'],
      ['Condition', 'Two small edge dings on the crash, no cracks'],
      ['Service', 'Cleaned and inspected'],
    ],
    tags: ['trade in', 'student', 'cymbal pack'],
    arrived: '2026-08-31',
    trade: true,
  }),

  /* ---- Band & orchestra ------------------------------------------- */
  define({
    sku: 'QM-BND-7101',
    slug: 'yamaha-yas-26-alto-saxophone',
    name: 'YAS-26 Alto Saxophone',
    brand: 'Yamaha',
    category: 'band-instruments',
    sub: 'Woodwind',
    short: 'The standard student alto, play-tested on our bench before it ships.',
    body: 'The standard student alto, and the one most band directors around here will tell you to get. Play-tested and adjusted on our bench before it goes out.',
    price: 219999,
    stock: 2,
    plate: 'band',
    alt: 'Yamaha YAS-26 student alto saxophone in case',
    specs: [
      ['Key', 'E flat'],
      ['Finish', 'Gold lacquer'],
      ['Included', 'Case, mouthpiece, ligature'],
      ['Service', 'Play-tested and adjusted in house'],
    ],
    tags: ['school band', 'saxophone', 'student'],
    arrived: '2026-06-30',
  }),
  define({
    sku: 'QM-BND-7102',
    slug: 'bach-tr300h2-trumpet-used',
    name: 'TR300H2 Trumpet',
    brand: 'Bach',
    category: 'band-instruments',
    sub: 'Brass',
    short: 'A student trumpet back from a few school years, cleaned and aligned.',
    body: 'A student trumpet traded back in after a few school years. Chemically cleaned, dents rolled out, valves free and fast. A sensible way into band without buying new.',
    price: 64999,
    condition: 'used',
    stock: 1,
    plate: 'band',
    alt: 'Used Bach TR300H2 student trumpet',
    specs: [
      ['Bore', '.459" medium large'],
      ['Service', 'Chem clean and valve alignment'],
      ['Condition', 'Lacquer wear at the valve casing'],
    ],
    tags: ['school band', 'trumpet', 'trade in'],
    arrived: '2026-09-04',
    trade: true,
  }),
  define({
    sku: 'QM-BND-7103',
    slug: 'eastman-vl80-violin-outfit',
    name: 'VL80 Violin Outfit',
    brand: 'Eastman',
    category: 'band-instruments',
    sub: 'Strings',
    short: 'A student violin outfit, set up with a fitted bridge before it leaves.',
    body: 'Solid carved top, ebony fittings, and a bridge we fit and cut here rather than leaving it in the box the way it arrived. Comes with a bow, case and rosin.',
    price: 54999,
    stock: 3,
    plate: 'band',
    alt: 'Eastman VL80 student violin outfit with bow and case',
    specs: [
      ['Size', '4/4'],
      ['Top', 'Solid carved spruce'],
      ['Fittings', 'Ebony'],
      ['Included', 'Bow, oblong case, rosin'],
      ['Setup', 'Bridge fitted and cut in house'],
    ],
    tags: ['orchestra', 'violin', 'student'],
    arrived: '2026-07-31',
  }),
  define({
    sku: 'QM-BND-7104',
    slug: 'yamaha-ycl-255-clarinet',
    name: 'YCL-255 Clarinet',
    brand: 'Yamaha',
    category: 'band-instruments',
    sub: 'Woodwind',
    short: 'The student clarinet most directors here put on the list.',
    body: 'The student clarinet most band directors around here put on the list. ABS resin body, so it survives a locker, and an adjustable thumb rest for smaller hands.',
    price: 84999,
    stock: 4,
    plate: 'band',
    alt: 'Yamaha YCL-255 student clarinet in case',
    // Demo photography: a real Yamaha clarinet — see
    // public/photos/demo/CREDITS.json.
    image: '/photos/demo/clarinet.jpg',
    specs: [
      ['Key', 'B flat'],
      ['Body', 'ABS resin'],
      ['Included', 'Case, mouthpiece, ligature, cap'],
      ['Service', 'Play-tested in house'],
    ],
    tags: ['school band', 'clarinet', 'student'],
    arrived: '2026-06-13',
  }),
  define({
    sku: 'QM-BND-7105',
    slug: 'rico-alto-sax-reeds-25',
    name: 'Alto Sax Reeds, Box of 25',
    brand: 'Rico',
    category: 'band-instruments',
    sub: 'Reeds',
    short: 'Reeds by the box, because they always run out mid-term.',
    body: 'Reeds by the box, because a student always runs out the week of a concert. Strength 2.5 is the usual starting point; ask us if you are not sure.',
    price: 4499,
    stock: 22,
    plate: 'band',
    alt: 'Box of 25 Rico alto saxophone reeds',
    specs: [
      ['Strength', '2.5'],
      ['Quantity', '25 per box'],
    ],
    tags: ['reeds', 'consumable', 'school band'],
    arrived: '2026-05-02',
  }),

  /* ---- Pro audio -------------------------------------------------- */
  define({
    sku: 'QM-PA-8101',
    slug: 'qsc-k12-2-powered-speaker',
    name: 'K12.2 Powered Speaker',
    brand: 'QSC',
    category: 'pro-audio',
    sub: 'Powered speaker',
    short: 'The box we put in front of more congregations than anything else.',
    body: 'The box we put in front of more congregations and school gyms than anything else. Clean at volume, light enough for one person, and it survives being loaded in and out every week.',
    price: 104999,
    stock: 4,
    plate: 'pro-audio',
    alt: 'QSC K12.2 powered PA speaker',
    specs: [
      ['Power', '2000 W peak, class D'],
      ['Driver', '12" woofer, 1.4" compression driver'],
      ['Coverage', '75 degrees conical'],
      ['Weight', '17.4 kg'],
      ['Presets', 'Six voicing presets with contour EQ'],
    ],
    tags: ['church', 'school', 'PA', 'install'],
    arrived: '2026-07-14',
    featured: true,
  }),
  define({
    sku: 'QM-PA-8102',
    slug: 'allen-heath-sq-5-digital-mixer',
    name: 'SQ-5 Digital Mixer',
    brand: 'Allen & Heath',
    category: 'pro-audio',
    sub: 'Mixing console',
    short: 'A console a volunteer can learn and an engineer will not complain about.',
    body: 'A console a volunteer can learn on and an engineer will not complain about. We install these, we set the scenes up, and we train the people who have to run them on a Sunday.',
    price: 429900,
    stock: 1,
    plate: 'pro-audio',
    alt: 'Allen & Heath SQ-5 digital mixing console',
    specs: [
      ['Channels', '48 input, 36 bus'],
      ['Preamps', '16 onboard XLR'],
      ['Latency', '0.7 ms'],
      ['Support', 'Installation and training available'],
    ],
    tags: ['install', 'church', 'console'],
    arrived: '2026-05-28',
    pickupOnly: true,
    enquiry: true,
  }),
  define({
    sku: 'QM-PA-8103',
    slug: 'yamaha-mg12xu-analog-mixer',
    name: 'MG12XU Analogue Mixer',
    brand: 'Yamaha',
    category: 'pro-audio',
    sub: 'Mixing console',
    short: 'Twelve channels of analogue that anybody can be taught in ten minutes.',
    body: 'Twelve channels, real knobs, and effects built in. When a room needs a desk that any volunteer can be taught in ten minutes, this is still the right answer.',
    price: 44999,
    stock: 3,
    plate: 'pro-audio',
    alt: 'Yamaha MG12XU twelve channel analogue mixer',
    // Demo photography: a real Yamaha analog mixing console, different
    // model — see public/photos/demo/CREDITS.json.
    image: '/photos/demo/mixing-console.jpg',
    specs: [
      ['Channels', '12'],
      ['Preamps', 'Six D-PRE microphone inputs'],
      ['Effects', 'SPX digital effects'],
      ['Interface', '2-in / 2-out USB'],
    ],
    tags: ['analogue', 'volunteer friendly', 'small venue'],
    arrived: '2026-08-11',
    isNew: true,
  }),
  define({
    sku: 'QM-PA-8104',
    slug: 'jbl-eon715-powered-speaker',
    name: 'EON715 Powered Speaker',
    brand: 'JBL',
    category: 'pro-audio',
    sub: 'Powered speaker',
    short: 'A fifteen-inch powered box with DSP you set from your phone.',
    body: 'A fifteen inch box with enough output for a mid-size room, and DSP you set up from a phone rather than by squinting at the back panel in the dark.',
    price: 79999,
    stock: 4,
    plate: 'pro-audio',
    alt: 'JBL EON715 fifteen inch powered PA speaker',
    specs: [
      ['Power', '1300 W peak'],
      ['Driver', '15" woofer, 1" compression driver'],
      ['Control', 'Bluetooth app with parametric EQ'],
    ],
    tags: ['PA', 'venue', 'portable'],
    arrived: '2026-06-26',
  }),
  define({
    sku: 'QM-PA-8105',
    slug: 'shure-blx24-sm58-wireless',
    name: 'BLX24/SM58 Wireless System',
    brand: 'Shure',
    category: 'pro-audio',
    sub: 'Wireless',
    short: 'A wireless handheld that will not drop out mid-sentence.',
    body: 'A wireless handheld with an SM58 capsule on it, and a receiver that finds a clear channel on its own. The system we fit when somebody needs to walk and talk.',
    price: 39900,
    stock: 3,
    plate: 'microphone',
    alt: 'Shure BLX24 wireless system with SM58 handheld transmitter',
    specs: [
      ['Capsule', 'SM58 cardioid dynamic'],
      ['Range', 'Up to 90 m line of sight'],
      ['Battery', 'Two AA, up to 14 hours'],
    ],
    tags: ['wireless', 'church', 'speech'],
    arrived: '2026-07-22',
  }),
  define({
    sku: 'QM-PA-8106',
    slug: 'behringer-powerplay-p2-iem',
    name: 'Powerplay P2 In-Ear Monitor Amp',
    brand: 'Behringer',
    category: 'pro-audio',
    sub: 'Monitoring',
    short: 'A belt-pack headphone amp for wired in-ear monitoring on a budget.',
    body: 'A belt-pack headphone amplifier for wired in-ear monitoring. The cheapest honest way to get a worship team off wedges and onto ears.',
    price: 4999,
    stock: 9,
    plate: 'pro-audio',
    alt: 'Behringer Powerplay P2 in-ear monitor belt pack amplifier',
    specs: [
      ['Input', 'Balanced XLR'],
      ['Power', 'Two AAA batteries or USB'],
      ['Output', '3.5 mm stereo'],
    ],
    tags: ['in ear', 'monitoring', 'worship'],
    arrived: '2026-05-11',
  }),

  /* ---- Microphones ------------------------------------------------ */
  define({
    sku: 'QM-MIC-8201',
    slug: 'shure-sm58',
    name: 'SM58',
    brand: 'Shure',
    category: 'microphones',
    sub: 'Dynamic',
    short: 'It will outlive the singer. Fifty years and nobody has replaced it.',
    body: 'It will outlive the singer. The default vocal microphone everywhere for fifty years, and there is a reason nobody has replaced it.',
    price: 10900,
    stock: 14,
    plate: 'microphone',
    alt: 'Shure SM58 dynamic vocal microphone',
    // Demo photography: a real handheld dynamic mic of this shape — see
    // public/photos/demo/CREDITS.json.
    image: '/photos/demo/microphone-1.jpg',
    specs: [
      ['Pattern', 'Cardioid'],
      ['Response', '50 Hz to 15 kHz'],
      ['Included', 'Clip and pouch'],
    ],
    tags: ['vocal', 'stage', 'indestructible'],
    arrived: '2026-04-08',
  }),
  define({
    sku: 'QM-MIC-8202',
    slug: 'audio-technica-at2020',
    name: 'AT2020',
    brand: 'Audio-Technica',
    category: 'microphones',
    sub: 'Condenser',
    short: 'A first condenser that sounds well beyond its price.',
    body: 'A first condenser for recording at home. Needs phantom power, rewards a quiet room, and sounds far better than its price suggests.',
    price: 9900,
    stock: 5,
    plate: 'microphone',
    alt: 'Audio-Technica AT2020 cardioid condenser microphone',
    // Demo photography: a real studio condenser mic in a shockmount — see
    // public/photos/demo/CREDITS.json.
    image: '/photos/demo/microphone-2.jpg',
    specs: [
      ['Pattern', 'Cardioid'],
      ['Requires', '48V phantom power'],
      ['Max SPL', '144 dB'],
    ],
    tags: ['home recording', 'condenser', 'podcast'],
    arrived: '2026-06-07',
  }),
  define({
    sku: 'QM-MIC-8203',
    slug: 'shure-sm57',
    name: 'SM57',
    brand: 'Shure',
    category: 'microphones',
    sub: 'Dynamic',
    short: 'On a snare, on a guitar cabinet, on a podium. Always.',
    body: 'On a snare, on a guitar cabinet, on a podium at a county meeting. If a room only owns one microphone that is not a vocal mic, it owns this.',
    price: 10900,
    stock: 11,
    plate: 'microphone',
    alt: 'Shure SM57 dynamic instrument microphone',
    specs: [
      ['Pattern', 'Cardioid'],
      ['Response', '40 Hz to 15 kHz'],
      ['Included', 'Clip and pouch'],
    ],
    tags: ['instrument', 'snare', 'amp mic'],
    arrived: '2026-04-08',
  }),
  define({
    sku: 'QM-MIC-8204',
    slug: 'rode-podmic-usb',
    name: 'PodMic USB',
    brand: 'Rode',
    category: 'microphones',
    sub: 'Dynamic',
    short: 'A broadcast dynamic that works over USB or XLR, whichever you have.',
    body: 'A broadcast-style dynamic that runs over USB into a laptop or XLR into a desk, so it survives you outgrowing the laptop. Forgiving in an untreated room.',
    price: 19900,
    stock: 4,
    plate: 'microphone',
    alt: 'Rode PodMic USB broadcast dynamic microphone',
    specs: [
      ['Connection', 'USB-C and XLR'],
      ['Pattern', 'Cardioid'],
      ['Processing', 'Onboard APHEX compressor and noise gate'],
    ],
    tags: ['podcast', 'streaming', 'usb'],
    arrived: '2026-08-23',
    isNew: true,
  }),

  /* ---- Accessories ------------------------------------------------ */
  define({
    sku: 'QM-ACC-9101',
    slug: 'elixir-nanoweb-light-acoustic-strings',
    name: 'Nanoweb Light Acoustic Strings',
    brand: 'Elixir',
    category: 'accessories',
    sub: 'Strings',
    short: 'Coated phosphor bronze that last about three times as long.',
    body: 'Coated phosphor bronze, 12 to 53. They last about three times as long as uncoated strings, which matters more than the price difference.',
    price: 1899,
    stock: 40,
    plate: 'accessory',
    alt: 'Elixir Nanoweb light gauge acoustic guitar strings pack',
    specs: [
      ['Gauge', '.012 - .053'],
      ['Material', 'Phosphor bronze, Nanoweb coating'],
    ],
    tags: ['strings', 'consumable', 'acoustic'],
    arrived: '2026-03-19',
  }),
  define({
    sku: 'QM-ACC-9102',
    slug: 'ernie-ball-regular-slinky-electric-strings',
    name: 'Regular Slinky Electric Strings',
    brand: 'Ernie Ball',
    category: 'accessories',
    sub: 'Strings',
    short: 'Ten to forty-six. The gauge most electric players default to.',
    body: 'Ten to forty-six, nickel wound, pink packet. The gauge most electric players default to without ever really deciding to.',
    price: 899,
    stock: 55,
    plate: 'accessory',
    alt: 'Ernie Ball Regular Slinky electric guitar strings pack',
    specs: [
      ['Gauge', '.010 - .046'],
      ['Material', 'Nickel-plated steel'],
    ],
    tags: ['strings', 'consumable', 'electric'],
    arrived: '2026-03-19',
  }),
  define({
    sku: 'QM-ACC-9103',
    slug: 'hercules-gs414b-guitar-stand',
    name: 'GS414B Guitar Stand',
    brand: 'Hercules',
    category: 'accessories',
    sub: 'Stands',
    short: 'The stand with the yoke that closes around the neck on its own.',
    body: 'The stand with the yoke that closes around the neck on its own. Buy one of these instead of leaning a guitar against the sofa.',
    price: 4499,
    stock: 0,
    plate: 'accessory',
    alt: 'Hercules GS414B auto-grip guitar stand',
    specs: [
      ['Fits', 'Electric, acoustic, and bass'],
      ['Feature', 'Auto Grip System yoke'],
    ],
    tags: ['stand', 'storage'],
    arrived: '2026-04-25',
  }),
  define({
    sku: 'QM-ACC-9104',
    slug: 'mono-m80-vertigo-guitar-case',
    name: 'M80 Vertigo Guitar Case',
    brand: 'Mono',
    category: 'accessories',
    sub: 'Cases',
    short: 'A gig bag that behaves like a case when a case will not fit the car.',
    body: 'A gig bag built like it expects to be dropped: a headstock suspension system, a boot that keeps the guitar off the floor, and a shell that takes a knock without passing it on.',
    price: 26999,
    stock: 3,
    plate: 'accessory',
    alt: 'Mono M80 Vertigo electric guitar gig bag',
    specs: [
      ['Fits', 'Most electric guitars'],
      ['Protection', 'Headstock suspension, Boot floor protection'],
      ['Carry', 'Backpack straps'],
    ],
    tags: ['case', 'gig bag', 'touring'],
    arrived: '2026-08-05',
    isNew: true,
  }),
  define({
    sku: 'QM-ACC-9105',
    slug: 'planet-waves-custom-series-cable',
    name: 'Custom Series Instrument Cable, 10ft',
    brand: "D'Addario",
    category: 'accessories',
    sub: 'Cables',
    short: 'A ten-foot cable that will not go crackly in a year.',
    body: 'Ten feet, moulded plugs, and it will not go crackly in a year. We keep a wall of these because a bad cable ruins more gigs than a bad amp.',
    price: 2999,
    stock: 30,
    plate: 'accessory',
    alt: "D'Addario Custom Series ten foot instrument cable",
    specs: [
      ['Length', '10 ft'],
      ['Connectors', 'Straight to straight, 1/4"'],
      ['Shielding', 'In-line molded'],
    ],
    tags: ['cable', 'consumable', 'gigging'],
    arrived: '2026-04-25',
  }),
  define({
    sku: 'QM-ACC-9106',
    slug: 'snark-st-8-clip-on-tuner',
    name: 'ST-8 Clip-On Tuner',
    brand: 'Snark',
    category: 'accessories',
    sub: 'Tuners',
    short: 'The clip-on tuner in every case in the building.',
    body: 'Clips on the headstock, reads the vibration rather than the sound, so it works in a loud room. There is one of these in nearly every case that comes through the door.',
    price: 1999,
    sale: 1499,
    stock: 25,
    plate: 'accessory',
    alt: 'Snark ST-8 clip-on chromatic tuner',
    specs: [
      ['Type', 'Chromatic, vibration sensing'],
      ['Display', 'Full-colour, rotating'],
    ],
    tags: ['tuner', 'gift', 'consumable'],
    arrived: '2026-05-16',
  }),
];

/* ------------------------------------------------------------------ */
/* Gallery density fixture                                            */
/* ------------------------------------------------------------------ */

/**
 * A guitar photographed properly has fifteen or twenty shots, so one product
 * gets that many images here to exercise the gallery at real density (the
 * brief calls for testing 10-20 images). Only the first is a verified real
 * photograph; the rest stay honest drawn plates with alt text describing the
 * angle a real photo shoot would cover, rather than repeating one photo
 * under false pretences.
 */
const galleryFixture = products.find((p) => p.slug === 'epiphone-es-335-figured');
if (galleryFixture) {
  const angles = [
    'Back of the body, showing the finish',
    'Headstock, front',
    'Headstock, back',
    'Neck join and heel',
    'Bridge and tailpiece, close up',
    'Pickups and control cavity',
    'F-hole and binding detail',
    'Serial number',
    'Case open, guitar inside',
    'Full length, leaning against an amp',
    'Fretboard, upper frets',
    'Strap buttons and jack socket',
    'Side profile, showing depth',
  ];
  galleryFixture.images = [
    galleryFixture.images[0],
    ...angles.map((alt) => ({ src: null, alt })),
  ];
}
